# Generated by Django 4.0.4 on 2022-07-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_rename_time_stamp_notification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
