# Generated by Django 4.0.4 on 2022-08-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0004_notification_targets_alter_notification_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PRIVATE', 'private'), ('PUBLIC', 'public')], default=('PRIVATE', 'private'), max_length=50),
        ),
    ]
