# Generated by Django 4.0.4 on 2022-08-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0005_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('PRIVATE', 'private'), ('PUBLIC', 'public'), ('GENERAL', 'general')], default=('PRIVATE', 'private'), max_length=50),
        ),
    ]
