# Generated by Django 4.0.4 on 2022-08-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='targets',
        ),
    ]
