# Generated by Django 4.0.4 on 2022-06-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_privatechatroom_unreadchatmessages_roomchatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessages',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
