# Generated by Django 4.0.4 on 2022-07-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_alter_unreadchatmessages_most_recent_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchatmessage',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='unreadchatmessages',
            name='most_recent_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
