# Generated by Django 4.0.4 on 2022-07-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_alter_roomchatmessage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreadchatmessages',
            name='most_recent_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
