# Generated by Django 4.0.4 on 2022-08-15 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0011_remove_publicchatroom_referral_token'),
        ('Chat', '0007_alter_unreadchatmessages_most_recent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreadchatmessages',
            name='public_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_room', to='Public.publicchatroom'),
        ),
        migrations.AlterField(
            model_name='unreadchatmessages',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='Chat.privatechatroom'),
        ),
    ]
