# Generated by Django 4.0.4 on 2022-08-20 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chat', '0010_alter_unreadchatmessages_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unreadchatmessages',
            name='users',
        ),
        migrations.AlterField(
            model_name='unreadchatmessages',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
