# Generated by Django 4.0.4 on 2022-07-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0002_alter_publicchatroom_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='uid',
            field=models.CharField(default='4K76MjL1', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
