# Generated by Django 4.0.4 on 2022-07-17 13:44

import Public.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0003_publicchatroom_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='image',
            field=models.ImageField(blank=True, default=Public.utils.default_public_room_image, max_length=1024, null=True, upload_to=Public.utils.public_room_image_file_path),
        ),
    ]
