# Generated by Django 4.0.4 on 2022-07-20 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Public', '0004_publicchatroom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
