# Generated by Django 4.0.4 on 2022-08-05 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0005_publicchatroom_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
