# Generated by Django 4.0.4 on 2022-08-06 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Public', '0006_publicchatroom_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='users who are connected to chat room.', related_name='room_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
