# Generated by Django 4.0.4 on 2022-08-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0008_alter_publicchatroom_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='referral_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
