# Generated by Django 4.0.4 on 2022-08-11 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Public', '0009_publicchatroom_referral_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='connect_users',
            field=models.ManyToManyField(blank=True, help_text='users who are connected to chat room.', related_name='connect_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicchatroom',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='chat room members.', related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
