# Generated by Django 4.0.4 on 2022-08-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Public', '0010_publicchatroom_connect_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicchatroom',
            name='referral_token',
        ),
    ]
